WITH T10 AS (
SELECT *
FROM [dbo].[ivy.mm.dim.posupc] 
WHERE LEN(UPC) >4 AND UPC IS NOT NULL),
-- extract legit UPC excluding characters & other unidentified upc numbers
T2 AS (
SELECT UPC, ACT_DATE, SUM(Gross_amt) AS SALES 
FROM [ivy.sd.fact.pos] 
WHERE ACT_DATE >= DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 4, 0) 
GROUP BY UPC, ACT_DATE),
-- Filter the recent 4 months data from date
T3 AS (
SELECT T1.UPC, T1.DIVISION, T2.ACT_DATE, T2.SALES 
FROM T2 
	LEFT JOIN [ivy.mm.dim.posupc] AS T1 ON T2.UPC = T1.UPC 
WHERE T1.DIVISION IS NOT NULL),
T4 AS (
SELECT UPC, DIVISION,
SUM(CASE WHEN ACT_DATE = DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 4, 0) THEN SALES ELSE 0 END) AS M4,
SUM(CASE WHEN ACT_DATE = DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 3, 0) THEN SALES ELSE 0 END) AS M3,
SUM(CASE WHEN ACT_DATE = DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 2, 0) THEN SALES ELSE 0 END) AS M2,
SUM(CASE WHEN ACT_DATE = DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 1, 0) THEN SALES ELSE 0 END) AS M1
FROM T3 
GROUP BY UPC, division),
-- Finding the recent 4 months sales data for a ranking system & hot item
T5 AS (
SELECT UPC, DIVISION,
M4, ROW_NUMBER() OVER (PARTITION BY DIVISION ORDER BY M4 DESC) AS R4,
M3, ROW_NUMBER() OVER (PARTITION BY DIVISION ORDER BY M3 DESC) AS R3,
M2, ROW_NUMBER() OVER (PARTITION BY DIVISION ORDER BY M2 DESC) AS R2,
M1, ROW_NUMBER() OVER (PARTITION BY DIVISION ORDER BY M1 DESC) AS R1
FROM T4 
WHERE M1>0 AND M2>0 AND M3>0 AND M4>0
),
T6 AS (
SELECT UPC, DIVISION, 
CASE WHEN
	(CAST(R4 AS int) - CAST(R3 AS int))>0 AND
	(CAST(R3 AS int) - CAST(R2 AS int))>0 AND
	(CAST(R2 AS int) - CAST(R1 AS int))>0 THEN 1 ELSE 0 END AS S
FROM T5),
LYD AS (
SELECT  A.UPC,  COUNT(DISTINCT A.SHIPTOPARTY) L1YR_DR, -- Last year distinct door # 
COUNT(DISTINCT (CASE WHEN A.ACT_DATE = DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 1, 0) THEN A.SHIPTOPARTY ELSE NULL END) ) L1M_DR, -- Last month distinct door # using case
SUM(A.gross_amt) L1YR_Sales, 
SUM(CASE WHEN A.ACT_DATE = DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 1, 0) THEN A.gross_amt ELSE NULL END) L1M_Sales,
SUM (A.qty) L1YR_Qty, 
SUM (CASE WHEN A.ACT_DATE = DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 1, 0) THEN A.qty ELSE NULL END) L1M_Qty
FROM [ivy.sd.fact.pos] AS A 
	LEFT JOIN [ivy.mm.dim.shiptoparty_pos] AS B ON A.SHIPTOPARTY = B.SHIPTOPARTY 
WHERE A.ACT_DATE >= DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 12, 0) AND B.ACTIVE='ACTIVE' 
GROUP BY UPC),
HI AS (SELECT UPC, CASE WHEN S=0 THEN 'REGULAR' ELSE 'HOT' END AS 'HOTITEM' FROM T6),
A2 AS (SELECT UPC, ACT_DATE, SUM(Gross_amt) SALES FROM [ivy.sd.fact.pos] WHERE ACT_DATE >= DATEADD(mm, DATEDIFF(mm, 0, GETDATE()) - 12, 0) GROUP BY UPC, ACT_DATE),
A3 AS (SELECT T1.UPC, T1.DIVISION, A2.ACT_DATE, A2.SALES FROM A2 LEFT JOIN [dbo].[ivy.mm.dim.posupc] T1 ON A2.UPC = T1.UPC WHERE T1.DIVISION IS NOT NULL),
A4 AS (SELECT UPC, DIVISION, ACT_DATE, SALES, RANK() OVER (PARTITION BY DIVISION, ACT_DATE ORDER BY SALES DESC) AS RK FROM A3),
R2 AS (SELECT UPC, COUNT(*) AS NUM200 FROM A4 WHERE RK <=200 GROUP BY DIVISION, UPC),
FT AS (
SELECT 
TT.plc,
T10.*,
HI.HOTITEM, 
LYD.L1M_DR, 
LYD.L1YR_DR,
LYD.L1YR_sales,
LYD.L1M_sales,
R2.NUM200,
CASE WHEN T10.KISS IS NOT NULL THEN 'https://**'+ T10.kiss
ELSE 'https://www.google.com/search?q=' + T10.upc + '&oq=34264028319&aqs=chrome..69i57.1069j0j9&sourceid=chrome&ie=UTF-8' END AS Hyperlink
FROM T10 
	LEFT JOIN LYD ON T10.upc = LYD.UPC 
	LEFT JOIN R2 ON T10.UPC = R2.upc 
	LEFT JOIN HI ON HI.upc = T10.UPC 
	LEFT JOIN (
	SELECT UPC, PLC 
	FROM [ivy.mm.dim.mtrl] 
	WHERE MS IN ('01', '91', '41')) AS TT ON T10.upc=TT.upc)

SELECT *
FROM FT;
